## <span style='color:darkblue'><strong>Power Of NumPy</strong></span>

In [1]:
# Import necessary modules
import numpy as np
import math

## <span style='color:grey'><strong>Understanding of 1D, 2D and 3D arrays</strong></span>

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr2 = np.array([[1, 2], [3, 4]])

print(arr2)

type(arr2)

[[1 2]
 [3 4]]


numpy.ndarray

In [7]:
arr2.shape

(2, 2)

In [15]:
arr3 = np.array([[[1, 2], [3,4]], [[5, 6],[7, 8]]])

arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
type(arr3)

arr3.shape

(2, 2, 2)

In [18]:
arr3.ndim

3

## <span style='color:grey'><strong>Difference between "arange" and "linespace" functions</strong></span>

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [20]:
np.arange(1, 5, 2)

array([1, 3])

In [21]:
np.linspace(1,9)

array([1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
       1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
       2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
       3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
       4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
       5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
       5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
       6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
       7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
       8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ])

In [22]:
np.linspace(1,9, 10)

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

## <span style='color:grey'><strong>Difference between the shallow copy and deep copy in numpy</strong></span>

In [23]:
arr2

array([[1, 2],
       [3, 4]])

In [25]:
shallowarr = arr2

deeparr = np.copy(arr2)

In [29]:
# Print the data from arrays
print('array 2 :',arr2)
print()
print('Shallow array :', shallowarr)
print()
print('Deep array :', deeparr)
print()

# Print Object id of arrays
print('array 2 object id :',id(arr2))
print()
print('Shallow array object id:', id(shallowarr))
print()
print('Deep array object id:', id(deeparr))

array 2 : [[1 2]
 [3 4]]

Shallow array : [[1 2]
 [3 4]]

Deep array : [[1 2]
 [3 4]]

array 2 object id : 2235510395152

Shallow array object id: 2235510395152

Deep array object id: 2233789906064


## <span style='color:grey'><strong>fromfunction in numpy</strong></span>

In [30]:
np.fromfunction(lambda i,j: i * j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [31]:
np.fromfunction(lambda i,j: i == j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [32]:
np.fromfunction(lambda i,j: i + j, (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

## <span style='color:grey'><strong>To create an identity matrix</strong></span>

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## <span style='color:grey'><strong>Reshape function in numpy</strong></span>

In [35]:
dataset = np.linspace(2, 9, 50)

dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [36]:
dataset.shape

(50,)

In [39]:
dataset.reshape(2, 1, 25)

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])